### ISSUE TITLE
SystemFonts.Find will throw, not return null

### ISSUE THREAD

**Issue by jsgoupil** [SixLabors/Fonts#129]
https://github.com/SixLabors/Fonts/blob/master/src/SixLabors.Fonts/SystemFonts.cs#L36
It says 
```
        /// <returns>The family if installed otherwise null</returns>
        public static FontFamily Find(string fontFamily) => Collection.Find(fontFamily);
```

This is not true, it will throw an exception.
Simply fix the help documentation. The TryFind is available.

**Comment by JimBobSquarePants** [comment]
@jsgoupil 

Please use the provided issue template when raising instructions.

**Comment by jsgoupil** [comment]
@JimBobSquarePants alright, then if that's too big of a deal understanding my bug report, you can handle it.

**Comment by JimBobSquarePants** [comment]
@jsgoupil That's a really disappointing attitude. 

We request individuals fill in the appropriate forms when raising issues because it helps us working on the library (in our spare time I might add with no obligation to you) to properly triage and prioritize issues. 

Not only that, it helps others (such as yourself) to determine whether an issue you are encountering is a known issue or a new one, whether a fix is in the works or has even been released.  

It's important that when you visit the repository of an open source project you abide by the rules of that repository. Help us, to help you and others.

**Comment by JimBobSquarePants** [comment]
Fixes via #130 Thanks @Turnerj

**Comment by jsgoupil** [comment]
@JimBobSquarePants I hope you feel better teaching me. I'm always happy when people find bugs in my software. If it goes a little bit out of what I'm looking for but I can still understand, I am happy someone took the time to improve the software I wrote.
Just chill.

**Comment by peter-dolkens** [comment]
Check out the Fedora on this guy!

No really. Check it out 🤣

**Comment by dlemstra** [comment]
@peter-dolkens There is no need for this kind of conversations.
