### ISSUE TITLE
'loop detected loading glyphs'

### ISSUE THREAD

**Issue by dotnetnoobie** [SixLabors/Fonts#21]
I get this error a lot if I try to use a .ttf font I have downloaded from Google Fonts
I have tried many different fonts and this is a common error with most of the fonts I have downloaded from Google Fonts

This is how I load the fonts
```C#
            var collection = new FontCollection();
            var font = collection.Install($"{_env.WebRootPath}\\fonts\\CarterOne.ttf");
```

This is using SixLabors.Fonts in ImageSharp.Drawing

  at SixLabors.Fonts.Tables.General.Glyphs.EmptyGlyphLoader.CreateGlyph(GlyphTable table)
   at SixLabors.Fonts.FontInstance.GetGlyph(Char character)
   at SixLabors.Fonts.TextLayout.GenerateLayout(String text, FontSpan style)
   at SixLabors.Fonts.TextMeasurer.MeasureText(String text, FontSpan style)

**Comment by tocsoft** [comment]
Looks like the font your using doesn't support one or more of the glyphs your trying to render and it doesn't provide a 'missing character glyph' glyph.

I've release a fix to stop the error when the 'missing character glyph' is not provided by rendering nothing instead.

The fix is in v0.1.0-alpha0006 (nuget.org) or v0.1.0-ci0056 (myget) depending on which feed your using.
