### ISSUE TITLE
DrawText generates text with DFKai-SB or KaiU fonts differently than expected

### ISSUE THREAD

**Issue by LoganChang** [SixLabors/Fonts#337]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Drawing
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

using chinese fonts on DrawText I got the error pic

### System Configuration

- ImageSharp.Drawing version:1.0.0-beta15
- Other ImageSharp packages and versions: 3.0.1
- .NET Framework version: .net 7
`       

           var font = SystemFonts.CreateFont(fontName, fontsize);
            var color = new Rgba32((byte)colorR, (byte)colorG, (byte)colorB);

            var image = new Image<Rgba32>(1, 1);
            var textSize = TextMeasurer.Measure(txt, new TextOptions(font));
            image.Mutate(x => x.Resize(new Size((int)textSize.Width, (int)textSize.Height)));
            image.Mutate(x => x.DrawText(txt, font, color, PointF.Empty));

            using (var stream = new MemoryStream())
            {
                image.Save(stream, new PngEncoder());
                return stream.ToArray();
            }
`

**Comment by JimBobSquarePants** [comment]
I'm going to need some help here. 

I had a look at the shaping using [Crowbar](https://www.corvelsoftware.co.uk/crowbar/) and it appears no GSUB substitutions take place. There's also no GPOS or KERN data in the font.

However, our output matches the colored glyphs on the right which clearly doesn't match the text in the input which matches what System.Drawing produces.

<img alt="image" src="https://github.com/SixLabors/ImageSharp.Drawing/assets/385879/25fbf3dc-d895-4475-bde2-8136f74a0317">

FontKit produces the same output we do and I don't know how to get HarfBuzz running in Visual Studio in order to run a unit test and debug.

I've attached the relevant font [kaiu.zip](https://github.com/SixLabors/ImageSharp.Drawing/files/11878002/kaiu.zip)

@behdad Sorry to tag you but is there something obvious I've missed?

**Comment by behdad** [comment]
Ah. Is it possible that it's one of those fonts that requires bytecode interpretter to be run to render correctly?

**Comment by behdad** [comment]
> Ah. Is it possible that it's one of those fonts that requires bytecode interpretter to be run to render correctly?

Doesn't look like it.

**Comment by behdad** [comment]
Indeed it's a difference between FreeType vs HarfBuzz outline extraction. Need to investigate more to see why.

**Comment by behdad** [comment]
> Ah. Is it possible that it's one of those fonts that requires bytecode interpretter to be run to render correctly?

If I drop the hinting then the FreeType rendering is broken as well.

**Comment by behdad** [comment]
I believe FreeType has logic to always enable the bytecode interpretter for fonts like this. Finding.

**Comment by behdad** [comment]
https://github.com/behdad/freetype/blob/08f66322e32cc882733dfae408e040f5057ee2ac/src/truetype/ttobjs.c#L181

**Comment by JimBobSquarePants** [comment]
Ah! @behdad you legend! 

I'd have never figured that out!

I need to do some work on how we handle composite glyphs and also make some changes to the hinter but local tests are very promising.

![image](https://github.com/SixLabors/Fonts/assets/385879/4ff504c3-9e9b-4eb0-b072-f99eb31f63c7)

**Comment by behdad** [comment]
Nice! So you have a hinter as well? Me is jealous.

**Comment by JimBobSquarePants** [comment]
I'm just standing on the shoulders of giants. 🙂
